DEVICE = iPhone5,1
BUILD = 10B350
PRODUCT = iBEC

RELOCATE_ADDR = 0x84000000

CFLAGS += -DTARGET_RELOCATE_ADDR=$(RELOCATE_ADDR)
CFLAGS += -I$(TARGETS_ROOT)/$(TARGET)/include

LDFLAGS += -Ttext=$(RELOCATE_ADDR)
